In [37]:
#Libraries
import pandas as pd
import plotly.express as px

import matplotlib
matplotlib.use("Agg")

import numpy as np

import re
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import sys
print(sys.executable)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


/opt/anaconda3/envs/lstm_env/bin/python


# Feedback 
Ser ut som dere er godt i gang, her er noen pinpoints jeg ville tatt med videre før siste innlevering 

1. Hvorfor importerere dere libraies flere ganger? Dere importerer de samme litt overalt i koden? Likevel har dere en block i toppen der det står libaries? Vær konsekvent, importer alle i toppen eller gjør det underveis. Men dere trenger ikke å importere de flere ganger ialfall. Gjør at oppgaven ser cleaner ut og bedre ut til innlvering
2. Dere kan gjerne ha litt refleksjon i oppgaven. Noen markdowns som forklarer hva som skjer i koden. Hvor gjør dere trening? Hvor begynner modellene? Hvor er EDA osv. 
3. Gjerne sett inn noen grafer og bilder. Kan dere bruker CM, loss, sammenligning osv
4. ser også at dere splitter data settet flere ganger? Hvorfor? Det er jo akk samme split hver gang? Evt hvis dere har behov for å gjøre det må dere forklare det. 
5. husk å justefy parameterene deres 
6. Hvis dere skal skrive kommentar og tekst i koden skriv engelsk slik at den som retter forstår hva som skjer
7. Sammenligning av resultater? Kanskje vudert å legge til en sammenligning av alt? 
8. LSTM bruker binary, noe som er annderledes fra de andre. Hvorfor brukes det? Hvordan kan dette da sammenlignes? Justify dette valget. Hvilke konsekvenser kan det ha 
9. Sjekk under data prep! NB! Her fit på hele datsettet!!!!!!!

Figures, Tables and Graphs

In [38]:


df = pd.read_csv("reviews.csv")


# sørg for riktige typer
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
df["helpful"] = pd.to_numeric(df["helpful"], errors="coerce").fillna(0).astype(int)

# dato: du har både mm/dd og dd/mm i eksempelet, så vi prøver begge
d1 = pd.to_datetime(df["review_date"], errors="coerce", dayfirst=False)
d2 = pd.to_datetime(df["review_date"], errors="coerce", dayfirst=True)
df["review_date"] = d1.fillna(d2)

df.head()

/var/folders/g4/yk6n2qr95jz52s70_0mf4ydw0000gn/T/ipykernel_66142/1157741725.py:10: UserWarning: Parsing dates in %m/%d/%Y %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  d2 = pd.to_datetime(df["review_date"], errors="coerce", dayfirst=True)


,review_id,rating,review_text,review_date,helpful
0,981e465b-d3ba-4632-9c60-25051efac38a,5,It's good,2025-11-22 01:19:00,0
1,964d3555-9429-4c20-8127-ce3c71ce9273,5,WhatsApp not working well always shows offline...,2025-11-24 20:03:00,0
2,6c28859f-1554-4ca1-9aa8-9d66f204be0a,5,"Oppo not corresponding, share with me the offi...",2025-11-25 06:26:00,0
3,a7efafc3-5871-4020-a398-9cc12cb4072a,5,"Excellent app, great communication super conne...",2025-11-25 18:09:00,0
4,de142b31-a5ad-446f-b7c8-51b264728478,4,simply the ɓest for chat and calls.i love it,2025-11-24 01:10:00,1


In [39]:
fig = px.histogram(df, x="rating", nbins=5, title="Fordeling av rating")
fig.show() #Omtrent halve datasettet har 5 i rating

In [40]:


upper_limit = df["helpful"].quantile(0.99)
df_filtered = df[df["helpful"] <= upper_limit]

fig = px.violin(df, x="rating", y="helpful", box=True, points=False, 
             title="Helpful Votes per Rating")
fig.update_yaxes(type='log')
fig.show()

# denne funket dårlig, viser opp mot over en million og videre selv om det er kun en som har nærmere 250k stemmer. utenom dette er resten under 10 000
# Tror ikke violin funker godt, må evt begrense parameterene og distansen

In [41]:
import numpy as np

upper_limit = df["helpful"].quantile(0.99)
df_filtered = df[df["helpful"] <= upper_limit]

fig = px.box(df_filtered, x="rating", y="helpful",
             title="Helpful Votes per Rating (Outliers Removed)")
fig.show()

# isolerer ut de med flest stemmer, altså blant annet den som har 250k stemmer

In [42]:
median_helpful = df.groupby("rating")["helpful"].median().reset_index()

fig = px.bar(median_helpful, x="rating", y="helpful",
             title="Median Helpful Votes per Rating")
fig.show()

#prøvde median, men denne ble skjevfordelt og flat på 0. Dette skyldes trolig at over halvparten av helpful dataen er 0

In [43]:
mean_helpful = df.groupby("rating")["helpful"].mean().reset_index()

fig = px.bar(mean_helpful, x="rating", y="helpful",
             title="Average Helpful Votes per Rating")
fig.show()

# viser gjenomsnittet av helpful. Blir dratt opp en del av de med mange stemmer. 
# Bruker mean for å fjerne de som fikk 0 i rating sånn at dataen blir mer representativ

In [44]:
# Sorter etter helpful votes synkende og ta topp 20
top_20_helpful = df.nlargest(20, 'helpful')[['rating', 'review_text', 'helpful']]
print(top_20_helpful)

      rating                                        review_text  helpful
4677       5  You are rolling out the reactions to messages ...   248962
1629       5  Please add an "edit status" feature.Also let's...     8696
5195       5  “I want WhatsApp to release an update in which...     4345
813        5  it's the Best messaging app I've used... it's ...     1884
4642       1  There is a major bug and privacy flaw where mu...     1688
4072       1        where is the scroll option for contact list      305
3115       2  5-star rating! WhatsApp is perfect for staying...      191
4082       3  I've noticed that when I start a new chat with...      188
6082       1  Many New features like Account Centre, Add Fac...      121
723        4  Love the app. But there's one bug that's been ...      113
2933       5  Can you add a feature to choose who can OPEN O...      101
703        2  good night i was using WhatsApp and I was bann...       95
4617       1  the about section character limit is 

In [45]:
# Beregn antall ord (enkel måte)
df['word_count'] = df['review_text'].str.split().str.len()

# Fjern ekstreme outliers for bedre visualisering
word_count_99 = df['word_count'].quantile(0.99)
helpful_99 = df['helpful'].quantile(0.99)

df_visual = df[(df['word_count'] <= word_count_99) & (df['helpful'] <= helpful_99)]

# Del ordantall inn i grupper
df_visual['word_group'] = pd.cut(df_visual['word_count'], 
                                 bins=[0, 10, 20, 30, 50, 75, 100, 200, 500],
                                 labels=['0-10', '11-20', '21-30', '31-50', '51-75', '76-100', '101-200', '201+'])

# Beregn gjennomsnittlig helpful per gruppe
avg_helpful_by_words = df_visual.groupby('word_group', observed=True)['helpful'].mean().reset_index()

# Visualiser med begrenset y-akse
fig = px.bar(avg_helpful_by_words, x='word_group', y='helpful',
             title='Gjennomsnittlig helpful score per ordantall',
             labels={'word_group': 'Antall ord i anmeldelsen', 
                    'helpful': 'Gjennomsnittlig helpful votes'})
fig.update_yaxes(range=[0, avg_helpful_by_words['helpful'].max() * 1.1])  # Begrens y-aksen
fig.show()

# Sjekk statistikken
print(avg_helpful_by_words)

/var/folders/g4/yk6n2qr95jz52s70_0mf4ydw0000gn/T/ipykernel_66142/3884750294.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_visual['word_group'] = pd.cut(df_visual['word_count'],


  word_group   helpful
0       0-10  0.174670
1      11-20  0.279919
2      21-30  0.322981
3      31-50  0.580220
4      51-75  0.810484
5     76-100  1.109375


Data Filtering

In [46]:


def detect_unwanted_reviews(text):
    if pd.isna(text):
        return {
            'is_valid': False,
            'reason': 'missing_text'}

    if text == '':
        return {
            'is_valid': False,
            'reason': 'No_text'}
    
    words = text.lower().split()
    word_count = len(words)

    #remove short reviews (3 or less words)
    if word_count <= 3:
        return {
            'is_valid': False,
            'reason': 'too_short'}
    
    #remove reviews containing the same number or word repetably (like '11111' or 'AAAAAA')
    text_without_space = re.sub(r'\s+', '',text)

    if len(text_without_space) >= 6:
        first_char = text_without_space[0]
        if all(c == first_char for c in text_without_space):
            return {
                'is_valid': False,
                'reason': 'repeating_characters'}
    
    #remove stings that are composed of random characters
    #like OZuZ05JvIrZcCzO8od8Qiogl3laDXMpBleqVst8K7 and swVXBcgpFzj0SCXRubdnhq7jiM0zO
    for word in words:
        if len(word) >= 20:
            return {
                'is_valid': False,
                'reason': 'too_long_word'}
    
    #remove the reviews that contains only one word which is repeated multiple times
    if word_count > 3:
        first_word = words[0]
        if all(w == first_word for w in words):
            return {
                'is_valid': False,
                'reason': 'repetetive_words'}
    
    stopwords = {'the', 'and', 'is', 'in', 'to', 'of', 'for', 'on', 'with', 
             'this', 'that', 'it', 'was', 'are', 'as', 'at', 'be', 'have',
             'from', 'or', 'by', 'not', 'but', 'what', 'all', 'when', 'I', 'you'}

    stopword_count = sum(1 for w in words if w in stopwords)
    stopword_ratio = stopword_count/word_count if word_count > 0 else 0

    if word_count > 10 and stopword_ratio < 0.08:
        return {
            'is_valid': False,
            'reason': 'few_stopwords'}
    
    return {
        'is_valid': True,
        'reason': 'valid_review'}
print()
print('Original dataset')
print()
print('Total amount of reviews: ',len(df))

df['detection_result'] = df['review_text'].apply(detect_unwanted_reviews)
df['is_valid'] = df['detection_result'].apply(lambda x: x['is_valid'])
df['filter_reason'] = df['detection_result'].apply(lambda x: x['reason'])

df_cleaned = df[df['is_valid']== True].copy()

print()
print('After filtering')
print()
print('Original amount of reviews: ', len(df))
print('Removed: ',len(df)- len(df_cleaned))
print('Amount of valid reviews: ', len(df_cleaned))
print('Reduction: ', round((len(df) - len(df_cleaned))/len(df)*100,1),'%')
print()
print('Reason for removal:')
print(df[~df['is_valid']]['filter_reason'].value_counts())



Original dataset

Total amount of reviews:  6210

After filtering

Original amount of reviews:  6210
Removed:  2019
Amount of valid reviews:  4191
Reduction:  32.5 %

Reason for removal:
filter_reason
too_short           1543
few_stopwords        278
repetetive_words     177
too_long_word         21
Name: count, dtype: int64


Data Cleaning

In [47]:
#datacleaning
def data_cleaning(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

stopwords = {'the', 'and', 'is', 'in', 'to', 'of', 'for', 'on', 'with', 
             'this', 'that', 'it', 'was', 'are', 'as', 'at', 'be', 'have',
             'from', 'or', 'by', 'not', 'but', 'what', 'all', 'when', 'I', 'you'}

def remove_stopwords(text):
    words = text.split()
    words = [w for w in words if w not in stopwords]
    return ' '.join(words)

df_cleaned['clean_text'] = df_cleaned['review_text'].apply(data_cleaning)
df_cleaned['clean_text'] = df_cleaned['clean_text'].apply(remove_stopwords)

Data Preparation

In [48]:
y = df_cleaned['rating']

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df_cleaned['clean_text'], y, test_size=0.2, random_state=42, stratify=y
)

tfidf = TfidfVectorizer(max_features=5000)
X_train = tfidf.fit_transform(X_train_text)
X_test = tfidf.transform(X_test_text)

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X_train_text)

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)

X_train_seq = pad_sequences(X_train_seq, maxlen=100, padding='post')
X_test_seq = pad_sequences(X_test_seq, maxlen=100, padding='post')

Four Machine Learning Models

Logistic Regression

In [49]:
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# --- PREDIKSJON ---
y_pred = model.predict(X_test)

# --- EVALUERING ---
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.3f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- CONFUSION MATRIX HEATMAP ---
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
            xticklabels=sorted(y.unique()), 
            yticklabels=sorted(y.unique()))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

# --- VIS NOEN EKSEMPLER ---
results = pd.DataFrame({
    "actual": y_test.values,
    "predicted": y_pred
})
print("\nEksempler på prediksjoner (første 10):")
print(results.head(10))

Accuracy: 0.640

Classification Report:
              precision    recall  f1-score   support

           1       0.56      0.73      0.63       255
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00        60
           4       1.00      0.01      0.03        71
           5       0.69      0.88      0.77       398

    accuracy                           0.64       839
   macro avg       0.45      0.32      0.29       839
weighted avg       0.58      0.64      0.56       839


Eksempler på prediksjoner (første 10):
   actual  predicted
0       1          1
1       5          5
2       5          5
3       5          5
4       1          1
5       1          5
6       2          5
7       5          5
8       2          5
9       1          1


/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", 

Naive Bayes

In [50]:
model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

results = pd.DataFrame({
    "actual": y_test.values,
    "predicted": y_pred
})

print(results.head(10))

Accuracy: 0.634088200238379
              precision    recall  f1-score   support

           1       0.57      0.70      0.62       255
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00        60
           4       0.00      0.00      0.00        71
           5       0.68      0.89      0.77       398

    accuracy                           0.63       839
   macro avg       0.25      0.32      0.28       839
weighted avg       0.49      0.63      0.55       839

   actual  predicted
0       1          5
1       5          5
2       5          5
3       5          5
4       1          1
5       1          5
6       2          5
7       5          5
8       2          5
9       1          5


/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", 

Random Forest

In [51]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=30,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

feature_names = tfidf.get_feature_names_out()
importances = model.feature_importances_

indices = np.argsort(importances)[-10:]

print("Viktigste ord:")
for i in indices:
    print(feature_names[i], importances[i])

Accuracy: 0.6293206197854588
              precision    recall  f1-score   support

           1       0.59      0.62      0.60       255
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00        60
           4       0.00      0.00      0.00        71
           5       0.65      0.93      0.76       398

    accuracy                           0.63       839
   macro avg       0.25      0.31      0.27       839
weighted avg       0.49      0.63      0.55       839

[[157   0   0   0  98]
 [ 34   0   0   0  21]
 [ 29   0   0   0  31]
 [ 18   0   0   0  53]
 [ 27   0   0   0 371]]
Viktigste ord:
its 0.010496477175188076
best 0.011476007330223064
nice 0.011932264873411315
whatsapp 0.012660814317649993
cant 0.013569720988754702
love 0.014314056456152312
very 0.014834367235042197
my 0.016997637992923982
good 0.024437002221180233
app 0.029370396569822897


/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", 

Long Short-Term Memory (LSTM)

In [52]:
X_train_seq = pad_sequences(X_train_seq, maxlen=100, padding='post')
X_test_seq = pad_sequences(X_test_seq, maxlen=100, padding='post')

y_train_binary = y_train.apply(lambda x: 1 if x >= 4 else 0)
y_test_binary = y_test.apply(lambda x: 1 if x >= 4 else 0)

model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=64, input_length=100))
model.add(LSTM(64))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.fit(X_train_seq, y_train_binary, epochs=5, batch_size=32, validation_split=0.2)

loss, acc = model.evaluate(X_test_seq, y_test_binary)
print("Accuracy:", acc)

/opt/anaconda3/envs/lstm_env/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/5
84/84 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 0.5565 - loss: 0.6883 - val_accuracy: 0.5663 - val_loss: 0.6852
Epoch 2/5
84/84 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5580 - loss: 0.6879 - val_accuracy: 0.5663 - val_loss: 0.6843
Epoch 3/5
84/84 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.5580 - loss: 0.6872 - val_accuracy: 0.5663 - val_loss: 0.6854
Epoch 4/5
84/84 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5580 - loss: 0.6871 - val_accuracy: 0.5663 - val_loss: 0.6850
Epoch 5/5
84/84 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5580 - loss: 0.6872 - val_accuracy: 0.5663 - val_loss: 0.6843
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5590 - loss: 0.6863
Accuracy: 0.5589988231658936


In [53]:


import numpy as np
import tensorflow as tf
import sklearn



print(np.__version__)
print(tf.__version__)
print(sklearn.__version__)

1.26.4
2.21.0
1.7.2
